server:
  port: 8083
spring:
  application:
    name: leyou-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.249.129:9300
      cluster-name: elasticsearch
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  rabbitmq:
    host: 192.168.249.129
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1