server:
  port: 8081
spring:
  application:
    name: leyou-item-service
  datasource:
    url: jdbc:mysql://192.168.249.129:3306/leyou
    username: root
    password: root
    hikari:
      max-lifetime: 2883000
      maximum-pool-size: 9
  rabbitmq:
    host: 192.168.249.129
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: leyou.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl